version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app